apiVersion: v1
kind: Service
metadata:
  name: seldon-webhook-service
  namespace: seldon-system
spec:
  selector:
    app: seldon-webhook
  ports:
  - name: http
    protocol: TCP
    port: 443
    targetPort: 8080