# apiVersion: machinelearning.seldon.io/v1
# kind: SeldonDeployment
# metadata:
#   name: mlflow-model
# spec:
#   protocol: v2
#   predictors:
#     - name: default
#       graph:
#         name: mlflow-model
#         type: MODEL
#       componentSpecs:
#         - spec:
#             containers:
#               - name: mlflow-model
#                 image: irismodel

apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  name: wines
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: gs://seldon-models/mlflow/elasticnet_wine_1.8.0
        name: classifier
      name: default
      replicas: 1